version: 1.0.{build}
image: Ubuntu2004

environment:
  GITHUB_TOKEN:
    secure: BIFCQO8UFzCOXFKhCgm+AHaLSLCRAiO4fEojZoc/woIEXJcK5mLFTnIp6HuI69np

install:
  - nvm install 18
  - nvm use 18
  - node -v
  - npm -v

build_script:
  - yarn install
  - yarn build

artifacts:
  - path: dist

