# Используем новый образ Ubuntu для поддержки Node.js и GLIBC
image: Ubuntu2004 

# Определяем окружение Node.js версии >=18.12.0
stack: node 18 

# Настройка веток, для которых будет выполняться сборка
branches:
  only:
    - main  

# Кэширование папки node_modules для ускорения установки
cache: node_modules  

# Установка зависимостей
install:
  - yarn install  

# Сборка при каждом коммите
build: on

# Запуск Webpack для сборки проекта
test_script:
  - yarn webpack

# Настройка деплоя на GitHub Pages
deploy:
  provider: Pages
  token: "${GITHUB_TOKEN}"  # Используем правильное обрамление
  local_dir: ./dist
  on:
    branch: main
