version: 1.0.{build}

environment:
  GITHUB_TOKEN:
    secure: BIFCQO8UFzCOXFKhCgm+AHaLSLCRAiO4fEojZoc/woIEXJcK5mLFTnIp6HuI69np

image: Ubuntu 22.04

build:
  verbosity: minimal

install:
  - yarn install

test_script:
  - yarn webpack

artifacts:
  - path: ./dist
